spring:
  config:
    activate:
      on-profile: dev
logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"

  level:
    br:
      com:
        fsales: info
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: debug
              ReactiveMongoTemplate: debug

