spring:
  application:
    name: @project.name@
    description: @project.version@
    version: @project.description@


  data:
    mongodb:
      auto-index-creation: true
      uri: ${NEX_STREAM_MONGODB_URI}
      database: ${NEX_STREAM_MONGODB_DATABASE}


logging:
  pattern:
    console: "%d{ABSOLUTE_MICROS} [%-5level] [%t] %c{1} - %msg%n"
  level:
    br:
      com:
        fsales: info


